name: Windows Companion

on:
  push:
    branches:
    - 'main'
    - 'win-cpn'
    paths:
    - '.github/workflow/win_cpn.yml'
    - 'companion/**'
    - 'tools/build-companion-nightly.sh'
  pull_request:
    branches:
    - 'main'
    - 'win-cpn'
    paths:
    - '.github/workflow/win_cpn.yml'
    - 'companion/**'
    - 'tools/build-companion-nightly.sh'

  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_GENERATOR: "MSYS Makefiles"

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git make mingw-w64-x86_64-toolchain

      - name: Install Dependencies
        run: |
          pacman -S --noconfirm mingw-w64-x86_64-qt5 \
                                mingw-w64-x86_64-cmake \
                                mingw-w64-x86_64-python-pip \
                                mingw-w64-x86_64-arm-none-eabi-gcc
          pip install Pillow
          
      - name: Build
        working-directory: ${{github.workspace}}
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          mkdir output && \
          tools/build-companion-nightly.sh $(pwd) $(pwd)/output/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: companion-nightly
          path:  ${{github.workspace}}/output
          retention-days: 15
