name: Windows Companion

on:
  push:
    branches:
    - 'main'
    paths:
    - '.github/workflow/win_cpn.yml'
    - 'companion/**'
    - 'tools/build-companion-nightly.sh'
  pull_request:
    branches:
    - 'main'
    paths:
    - '.github/workflow/win_cpn.yml'
    - 'companion/**'
    - 'tools/build-companion-nightly.sh'

  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git cmake mingw-w64-x86_64-toolchain

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Install Dependencies
        run: |
          pacman -S --noconfirm mingw-w64-x86_64-qt5
          pacman -S --noconfirm mingw-w64-ucrt-x86_64-winpthreads-git
          python -m pip install --upgrade pip Pillow
          
      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: mkdir ${{github.workspace}}/output && tools/build-companion-nightly.sh ${{github.workspace}}  ${{github.workspace}}/output/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: companion-nightly
          path:  ${{github.workspace}}/output
          retention-days: 15
